name: Build and Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Restore Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Build
        run: nix build .
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'result'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
